### ISSUE TITLE
Invalid BSON field when running in Mongo Atlas cluster

### ISSUE THREAD

**Issue by acnacion87** [ozwolf-software/mongo-trek#8]
Hi,

We are testing mongo-trek in Mongo Atlas cluster and we are getting this exception:
```
Caused by: java.lang.IllegalArgumentException: Invalid BSON field name $clusterTime
	at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:532) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:198) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:182) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:199) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:141) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:398) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.BulkWriteBatch$WriteRequestEncoder.encode(BulkWriteBatch.java:377) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[mongo-java-driver-3.8.0.jar:?]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:75) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:143) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:57) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:244) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:444) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:200) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:418) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:256) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation.access$700(MixedBulkWriteOperation.java:67) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:200) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:191) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.OperationHelper.withReleasableConnection(OperationHelper.java:419) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:191) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:67) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:193) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:960) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:602) ~[mongo-java-driver-3.8.0.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:578) ~[mongo-java-driver-3.8.0.jar:?]
	at net.ozwolf.mongo.migrations.internal.dao.DefaultSchemaVersionDAO.save(DefaultSchemaVersionDAO.java:58) ~[mongo-trek-3.0.0.jar:?]
```

**Comment by acnacion87** [comment]
The issue seems to happen on MongoTrek.java line 200:

**Comment by acnacion87** [comment]
Looks like this is introduced in MongoDB 3.6:
https://docs.mongodb.com/manual/reference/method/db.runCommand/

Perhaps remove this field from the result document if present when saving schema version document?

**Comment by OzWolf** [comment]
Sorry, I've been on an extended holiday for a while and just got back to the land of the internet.

I will look into stripping the $ prefix from keys in the result document as a first step.

**Comment by OzWolf** [comment]
I believe I have fixed this issue.  If `3.0.1` (when it becomes available via Maven Central) does not fix the bug as expected, feel free to re-open this issue.
